"""Markdown reporter: generates `.ai-inventory.md` for committing to the repo.

This artifact serves two purposes:
  1. Documentation in the repo — anyone browsing the repo sees the AI surfaces.
  2. Diff baseline for the GitHub Action — PRs compare new scan against this file.

Security notes (the report renders attacker-controlled source code into a
document that will be posted as a PR comment on GitHub):

* Snippets are wrapped in a length-aware code fence. The fence is sized to be
  longer than any backtick run inside the snippet so the attacker cannot break
  out of the fence with a literal ``` ``` ``` line.
* Strings that flow into markdown headings / bullets (``surface``,
  ``permissions``, ``risk_indicators``, file paths) are stripped of control
  characters and have leading markdown structural characters escaped.
* HTML tags in those strings are inert when rendered through GitHub's comment
  renderer (which sanitises HTML), but we still strip ``<`` / ``>`` from
  surface strings as defence in depth.
"""
from __future__ import annotations

from ..cross_promo import build_upgrade_url, headline_finding, specialists_for_report
from ..frameworks import standards_for_flag
from ..types import (
    CATEGORY_AGENT_FRAMEWORK,
    CATEGORY_AI_INFRA,
    CATEGORY_API,
    CATEGORY_ENV_KEY,
    CATEGORY_LLM_SDK,
    CATEGORY_MCP_SERVER,
    CATEGORY_MODEL_GATEWAY,
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
    SEVERITY_INFO,
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    Finding,
    Report,
)
from ..utils.markdown_safety import safe_fence as _safe_fence
from ..utils.markdown_safety import sanitise_inline as _sanitise_inline

CATEGORY_HEADING: dict[str, str] = {
    CATEGORY_LLM_SDK: "LLM SDK Call Sites",
    CATEGORY_AGENT_FRAMEWORK: "Agent Frameworks",
    CATEGORY_MCP_SERVER: "MCP Servers",
    CATEGORY_MODEL_GATEWAY: "Model Gateways",
    CATEGORY_AI_INFRA: "AI Infrastructure",
    CATEGORY_ENV_KEY: "AI Provider API Keys (env)",
    CATEGORY_API: "API Endpoints",
}

CATEGORY_ORDER: list[str] = [
    CATEGORY_LLM_SDK,
    CATEGORY_AGENT_FRAMEWORK,
    CATEGORY_MCP_SERVER,
    CATEGORY_MODEL_GATEWAY,
    CATEGORY_AI_INFRA,
    CATEGORY_ENV_KEY,
    CATEGORY_API,
]

# Emoji severity labels for GitHub-flavored markdown badges. Discovery-only
# findings (severity None) get no badge; absence of severity is meaningful.
SEVERITY_BADGE: dict[str, str] = {
    SEVERITY_CRITICAL: "🔴 CRITICAL",
    SEVERITY_HIGH: "🟠 HIGH",
    SEVERITY_MEDIUM: "🟡 MEDIUM",
    SEVERITY_LOW: "🔵 LOW",
    SEVERITY_INFO: "⚪ INFO",
}

_SEVERITY_DISPLAY_ORDER = (
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
    SEVERITY_MEDIUM,
    SEVERITY_LOW,
    SEVERITY_INFO,
)


def render_markdown(report: Report) -> str:
    """Render `report` as a markdown document suitable for committing."""
    out: list[str] = []
    out.append("# AI Inventory")
    out.append("")
    out.append(
        f"> Generated by [ai-surface](https://github.com/apisec-inc/AI-Surface) "
        f"v{report.tool_version}. Schema {report.schema_version}."
    )
    out.append(f"> Scan timestamp: `{report.scan_timestamp}`")
    out.append("")

    surface_count = len(report.findings)
    risk_count = sum(len(f.risk_indicators) for f in report.findings)
    out.append(
        f"**Production AI surfaces:** {surface_count}  "
        f"·  **Risk indicators:** {risk_count}"
    )
    out.append("")

    # Severity breakdown from the report summary (audited findings only).
    summary = report.summary or report.build_summary()
    if summary.by_severity:
        sev_bits = [
            f"{SEVERITY_BADGE.get(sev, sev.upper())} {summary.by_severity[sev]}"
            for sev in _SEVERITY_DISPLAY_ORDER
            if summary.by_severity.get(sev)
        ]
        if sev_bits:
            out.append("**Severity:** " + "  ·  ".join(sev_bits))
            out.append("")

    if not report.findings:
        out.append("No production AI surfaces detected at scan time.")
        out.append("")
        _append_footer(out, report)
        return "\n".join(out)

    by_cat = report.by_category()
    for cat in CATEGORY_ORDER:
        if cat in by_cat and by_cat[cat]:
            _append_category(out, cat, by_cat[cat])

    # Forward compatibility for unknown categories
    for cat, findings in by_cat.items():
        if cat not in CATEGORY_ORDER:
            _append_category(out, cat, findings)

    _append_risk_summary(out, report)
    _append_footer(out, report)
    return "\n".join(out)


def _append_category(out: list[str], category: str, findings: list[Finding]) -> None:
    heading = CATEGORY_HEADING.get(category, category.replace("-", " ").title())
    out.append(f"## {heading}")
    out.append("")
    for finding in findings:
        _append_finding(out, finding)
    out.append("")


def _append_finding(out: list[str], finding: Finding) -> None:
    # Audited findings carry a severity badge in the heading; discovery-only
    # findings (severity None) render exactly as before.
    heading = _sanitise_inline(finding.surface)
    if finding.severity:
        badge = SEVERITY_BADGE.get(finding.severity, finding.severity.upper())
        heading = f"{badge} {heading}"
    out.append(f"### {heading}")
    out.append("")

    # API endpoint metadata (method/path/auth/framework) from evidence.metadata.
    if finding.category == CATEGORY_API:
        _append_api_metadata(out, finding)

    if finding.evidence and finding.evidence.files:
        files = finding.evidence.files
        if len(files) <= 5:
            file_list = ", ".join(f"`{_sanitise_inline(f)}`" for f in files)
        else:
            file_list = (
                ", ".join(f"`{_sanitise_inline(f)}`" for f in files[:3])
                + f", and {len(files) - 3} more"
            )
        out.append(f"**Files:** {file_list}")
        out.append("")

    if finding.permissions:
        perms = ", ".join(f"`{_sanitise_inline(p, max_len=80)}`" for p in finding.permissions)
        out.append(f"**Tools/permissions:** {perms}")
        out.append("")

    models = finding.evidence.metadata.get("models_used") if finding.evidence else None
    if models:
        models_str = ", ".join(f"`{_sanitise_inline(m, max_len=80)}`" for m in models)
        out.append(f"**Models:** {models_str}")
        out.append("")

    if finding.risk_indicators:
        out.append("**Risk indicators:**")
        out.append("")
        for risk in finding.risk_indicators:
            out.append(f"- ⚠️ {_sanitise_inline(risk)}")
        out.append("")
        # Inline per-finding deep link to APIsec validation, with finding context.
        url = build_upgrade_url(finding, source="ai-surface", medium="markdown")
        out.append(f"[Validate this surface →]({url})")
        out.append("")

    # Deep-dive audit block (risk flags, secrets, trust) when present.
    if finding.audit is not None:
        _append_audit(out, finding)

    if finding.evidence and finding.evidence.snippet:
        snippet = finding.evidence.snippet.strip()
        if snippet:
            # Length-aware fence: a snippet containing ``` cannot break out
            # of the code block because we choose a fence longer than the
            # longest backtick run inside the body.
            fence, body = _safe_fence(snippet)
            out.append(fence)
            out.append(body)
            out.append(fence)
            out.append("")

    # Paid-platform upgrade bridges (the funnel).
    _append_bridges(out, finding)


def _append_api_metadata(out: list[str], finding: Finding) -> None:
    """Render method + path + auth/framework for an API-category finding."""
    meta = finding.evidence.metadata if finding.evidence else {}
    method = _sanitise_inline(str(meta.get("method", "")), max_len=16)
    path = _sanitise_inline(str(meta.get("path", "")), max_len=200)
    if method or path:
        endpoint = f"{method} {path}".strip()
        out.append(f"**Endpoint:** `{endpoint}`")
        out.append("")

    extras: list[str] = []
    framework = meta.get("framework")
    if framework:
        extras.append(f"**Framework:** `{_sanitise_inline(str(framework), max_len=40)}`")
    auth = meta.get("auth")
    if auth:
        extras.append(f"**Auth:** `{_sanitise_inline(str(auth), max_len=40)}`")
    source_spec = meta.get("source_spec")
    if source_spec:
        extras.append(f"**Spec:** `{_sanitise_inline(str(source_spec), max_len=120)}`")
    if extras:
        out.append("  ·  ".join(extras))
        out.append("")


def _append_audit(out: list[str], finding: Finding) -> None:
    """Render the deep-dive audit block: risk flags, secrets, trust.

    Secrets render NAME/TYPE/location only. Per the privacy guarantee there is
    never a secret value in the report; we never read or print one.
    """
    audit = finding.audit
    if audit is None:
        return

    if audit.risk_flags:
        out.append("**Audit risk flags:**")
        out.append("")
        for rf in audit.risk_flags:
            badge = SEVERITY_BADGE.get(rf.severity, rf.severity.upper())
            line = f"- {badge} **{_sanitise_inline(rf.flag, max_len=80)}**"
            if rf.description:
                line += f": {_sanitise_inline(rf.description)}"
            out.append(line)
            if rf.owasp:
                owasp = ", ".join(f"`{_sanitise_inline(o, max_len=20)}`" for o in rf.owasp)
                out.append(f"  - OWASP: {owasp}")
            standards = standards_for_flag(rf.flag)
            if standards:
                gov = ", ".join(
                    f"{_sanitise_inline(s['framework'], max_len=30)} "
                    f"{_sanitise_inline(s['clause'], max_len=20)}"
                    for s in standards
                )
                out.append(f"  - Governance: {gov}")
            if rf.remediation:
                out.append(f"  - Fix: {_sanitise_inline(rf.remediation)}")
        out.append("")

    if audit.secrets:
        # NAME and TYPE only; never a value.
        out.append("**Secrets detected (names/types only, no values):**")
        out.append("")
        for secret in audit.secrets:
            bits = [f"`{_sanitise_inline(secret.name, max_len=120)}`"]
            if secret.secret_type:
                bits.append(f"type `{_sanitise_inline(secret.secret_type, max_len=40)}`")
            if secret.confidence:
                bits.append(f"confidence {_sanitise_inline(secret.confidence, max_len=20)}")
            if secret.location:
                bits.append(f"at `{_sanitise_inline(secret.location, max_len=120)}`")
            sev = (
                f"{SEVERITY_BADGE.get(secret.severity, secret.severity.upper())} "
                if secret.severity
                else ""
            )
            out.append(f"- {sev}" + " · ".join(bits))
        out.append("")

    if audit.trust_label:
        trust = f"**Trust:** {_sanitise_inline(audit.trust_label, max_len=40)}"
        if audit.trust_score is not None:
            trust += f" ({audit.trust_score:g}/100)"
        out.append(trust)
        out.append("")


def _append_bridges(out: list[str], finding: Finding) -> None:
    """Render the paid-platform upgrade bridges for a finding as links."""
    for bridge in finding.bridges:
        label = _sanitise_inline(bridge.label, max_len=120)
        out.append(f"[Validate at runtime: {label} →]({bridge.url})")
        out.append("")


def _append_risk_summary(out: list[str], report: Report) -> None:
    risks = report.all_risk_indicators()
    if not risks:
        return
    out.append("## Risk Indicator Summary")
    out.append("")
    for r in risks:
        out.append(f"- ⚠️ {_sanitise_inline(r)}")
    out.append("")


def _append_footer(out: list[str], report: Report) -> None:
    out.append("---")
    out.append("")

    # Lateral cross-promotion to OSS specialists (mcp-audit, etc.) for the
    # categories present in the report. Only renders shipped specialists.
    specialists = specialists_for_report(report.findings)
    for spec in specialists:
        out.append(f"- {spec['tagline'].capitalize()}: [{spec['tool']}]({spec['url']})")
    if specialists:
        out.append("")

    headline = headline_finding(report.findings)
    upgrade_url = build_upgrade_url(headline, source="ai-surface", medium="markdown")
    out.append(
        "Validate which of these surfaces are exploitable in a running application: "
        f"[apisec.ai/products]({upgrade_url})"
    )
    out.append("")

    # Runtime validation routes available from this scan (report.summary).
    summary = report.summary or report.build_summary()
    if summary.bridges_available:
        out.append("### Validate at runtime in APIsec")
        out.append("")
        skus = ", ".join(f"`{_sanitise_inline(s, max_len=40)}`" for s in summary.bridges_available)
        out.append(f"Runtime validation routes available from this scan: {skus}")
        out.append("")
